install.packages("tidyverse")
library(tidyverse)
om<-read.csv("C:/Users/Ashraf/Desktop/SDBI Stuff/R/F.csv")
names(om)
head(om,18)
#convert the dat frame to a tibble for better readability(Basically SQL jaisa)
tibble::as_tibble(om)
glimpse(om)
str(om)
om %>% filter(CountryCode == "AUS" & Medal == "Gold" & Sex == "Women")
om %>% filter(CountryCode == "AUS" & (Medal == "Gold"| Medal == "Silver")) 
om %>% select(Sport, Event, CountryCode)
om %>% filter(CountryCode=="AUS" & Medal =="Gold") %>% select(Event)
om %>% filter(CountryCode=="AUS" & Medal =="Gold") %>% select(Event, Country = CountryCode)
om %>% arrange(ResultInSeconds) %>% filter(CountryCode=="AUS" & (Medal =="Gold"|Medal == "Silver")) %>% select(CountryCode,Sport,Medal,ResultInSeconds)
om %>% arrange(desc(ResultInSeconds)) %>% filter(CountryCode=="AUS" & (Medal =="Gold"|Medal == "Silver")) %>% select(CountryCode,Sport,Medal,ResultInSeconds)
om %>% select(GDP.2011,pop.2010) %>% mutate(GDP_per_Capita = GDP.2011/pop.2010)
om<- om %>% mutate(Gold = ifelse(Medal =="Gold",1,0),Silver= ifelse(Medal =="Silver",1,0),Bronze= ifelse(Medal=="Bronze",1,0))
str(om)
om %>% count(Gold == 1)
om %>% filter(CountryCode=="AUS") %>% count(Gold ==1) 
summary(om$Gold)
om %>% summarise(n=n(),sum_gold=sum(Gold),median_gold=median(Gold),mean_gold= mean(Gold),var_gold=var(Gold),sd_Gold=sd(Gold))
om<- rename(om,Category = Event)
str(om)
om %>% group_by(CountryCode) %>% summarise(n=n(), Total_Gold= sum(Gold),Total_Silver = sum(Silver), Total_Bronze = sum(Bronze))
om %>% group_by(CountryCode) %>% summarise(n=n (),Total_Medals = sum(Gold+Silver+Bronze))
om %>% group_by(Medal) %>% count(Sport) %>% top_n(1,n)
om %>% group_by(Medal) %>% count(Sport)                                           
